server:
  port: 8007
  servlet:
    context-path: /bootlin

management:
  endpoint:
    health:
      show-details: always
      enabled: true
    metrics:
      enabled: true
    loggers:
      enabled: true
    info:
      enabled: true
    threaddump:
      enabled: true
    mappings:
      enabled: true